// ==UserScript==
// @name         Hide Annoying BitBucket Diffs Fork
// @namespace    https://github.com/reyronald/hide-annoying-bitbucket-diffs/
// @version      1
// @description  Hides bulky diff blocks for autogenerated files in BitBucket pull requests using RegExp patterns defined by clear-text resource
// @author       Ronald Rey (reyronald@gmail.com)
// @match        https://*.bitbucket.org/*/pull-requests/*
// @match        https://*.bitbucket.org/*/commits/*
// ==/UserScript==

function replaceFontFamily() {
    const css = 'code { font-family: Consolas,Menlo,"Liberation Mono",Courier,monospace; }';
    const head = document.head || document.getElementsByTagName('head')[0];
    const style = document.createElement('style');

    style.type = 'text/css';
    if (style.styleSheet) {
        style.styleSheet.cssText = css;
    } else {
        style.appendChild(document.createTextNode(css));
    }

    head.appendChild(style);
}

(function() {
    'use strict';

    replaceFontFamily();

    const textSource = `
.xsd$
.wsdl$
Reference.cs$
Reference.svcmap$
.datasource
.disco$
.svcinfo$
.svg$
.jpg$
.bmp$
.png$
.gif$
.cur$
.eot$
.ttf$
.woff$
.resx$
package-lock.json
`.trim();

    const patterns = textSource.split(/\r?\n/).map((pattern) => new RegExp(pattern));

    const timer = setInterval(function() {
        const filesChanged = [...document.querySelectorAll('#commit-files-summary > li')].map(li => {
            const filename = li.getAttribute('data-file-identifier');

            if (patterns.some(re => re.test(filename))) {
                const span = document.createElement('span');
                span.style = "margin-left: 5px;";
                span.innerText = filename;
                li.querySelector('a').replaceWith(span);
            }

            return filename;
        });
        const filesToRemove = filesChanged.filter(filename => patterns.some(re => re.test(filename)));

        if (filesChanged.length) {
            clearInterval(timer);

            document.querySelector('#pullrequest-diff > section > h1').innerHTML += ` - Showing ${filesChanged.length - filesToRemove.length} of ${filesChanged.length}`;

            // TODO: Replace this setTimeout approach with some kind of DOM Observer
            // NOTE TO SELF: When completed,test with the file 
            // `/ProdoctivitySvc/ProdoctivityClientService9.xsd` in the PR
            // https://bitbucket.org/novosit/prodoctivity/pull-requests/371?w=1
            setTimeout(function() {
                filesToRemove.forEach(filename => {
                    const diffBlock = document.querySelector(`section[data-identifier="${filename}"]`);
                    if (diffBlock !== null) {
                       diffBlock.remove();
                    }
                });
            }, 1000);
        }
    }, 500);
})();
