// ==UserScript==
// @name         Hide Annoying BitBucket Diffs
// @namespace    http://sagegerard.com
// @version      0.1
// @description  Hides bulky diff blocks for autogenerated files in BitBucket pull requests using RegExp patterns defined by clear-text resource
// @author       Sage Gerard
// @match        https://bitbucket.org/*
// @resource     ignorePatterns http://pastebin.com/5mNJ0FHv 
// @grant        GM_getResourceText
// ==/UserScript==

(function() {
    'use strict';

    let observer, watch, diffContainer;

    const removeMatchingDiffs = () => {
        observer.disconnect(); // Prevent callback from triggering itself.

        const diffBlocks = document.querySelectorAll('.bb-udiff');
        const len = diffBlocks.length;

        const textSource = GM_getResourceText("ignorePatterns");

        if (!textSource) {
            console.log('[HABD] Could not load ignore patterns to hide BitBucket diffs, or no patterns were defined. Check your resource?');
            return;
        }

        const patterns = textSource.split(/\r?\n/).map((pattern) => new RegExp(pattern));

        if (len > 0) {
            for (let i = 0; i < len; ++i) {
                const db = diffBlocks[i];
                const filename = db.getAttribute('data-filename').trim();

                if (patterns.some(re => re.test(filename))) {
                    db.remove();
                    console.log('[HABD] Removed ', filename);
                }
            }
        }

        watch(); // Resume monitoring
    };

    observer = new MutationObserver(removeMatchingDiffs);

    // Make sure diff container exists before monitoring it for changes.
    const timer = setInterval(()=> {
        diffContainer = document.querySelector('#changeset-diff');

        if (diffContainer !== null) {
            watch = observer.observe.bind(observer, document.querySelector('#changeset-diff'), {
                childList: true,
                attributes: false,
                characterData: false
            });

            watch();
            removeMatchingDiffs();
            clearInterval(timer);
        }
    }, 500);
})();
